// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

import XCTest
@testable import ShortNerdCat // adjust to the real module name if different

// NOT YET WIRED INTO THE XCODE PROJECT. Written and reference-checked
// 2026-08-17 alongside the Kotlin port (BinlogTest.kt, which WAS run and
// passed against the same reference vectors) but could not be executed in
// this environment -- no Swift/Xcode toolchain available on Windows. Add
// this file to a test target (or create one) in ShortNerdCat.xcodeproj and
// run it on a real Mac before trusting the Swift Binlog port the way the
// Kotlin one is now verified.
//
// Verifies Binlog.appendRecord (SwiftLog.swift) produces byte-identical
// output to the real Go implementation (tunnel_cat/binlog.AppendRecord) for
// the same inputs. These expected hex strings were generated by actually
// running the Go code (`binlog.AppendRecord(nil, tag, []byte(payload))`),
// not derived by re-deriving the algorithm a second time -- a hand-ported
// CRC16/uvarint implementation is exactly the kind of thing that can look
// plausible while being subtly wrong, so this cross-checks against a real
// reference rather than trusting the port by inspection.
final class BinlogTests: XCTestCase {

    private func fromHex(_ s: String) -> [UInt8] {
        var bytes: [UInt8] = []
        var idx = s.startIndex
        while idx < s.endIndex {
            let next = s.index(idx, offsetBy: 2)
            bytes.append(UInt8(s[idx..<next], radix: 16)!)
            idx = next
        }
        return bytes
    }

    func testMatchesGoReference_tagSystem_shortAscii() {
        let got = Binlog.appendRecord(tag: 7, payload: [UInt8]("hello".utf8))
        XCTAssertEqual(got, fromHex("c5a7070568656c6c6f68e97a5c"))
    }

    func testMatchesGoReference_tagSystem_realLogLine() {
        let payload = "2026/08/17 10:39:05 [kl] user: connect button pressed\n"
        let got = Binlog.appendRecord(tag: 7, payload: [UInt8](payload.utf8))
        XCTAssertEqual(
            got,
            fromHex(
                "c5a70736323032362f30382f31372031303a33393a3035205b6b6c5d20757365723a20636f6e6e65637420" +
                "627574746f6e20707265737365640a49067a5c"
            )
        )
    }

    func testMatchesGoReference_tagGeneric_emptyPayload() {
        let got = Binlog.appendRecord(tag: 0, payload: [])
        XCTAssertEqual(got, fromHex("c5a700001d0f7a5c"))
    }

    func testMatchesGoReference_tagSocks5_singleByte() {
        let got = Binlog.appendRecord(tag: 2, payload: [UInt8]("a".utf8))
        XCTAssertEqual(got, fromHex("c5a7020161ed4a7a5c"))
    }
}
