// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

package com.shortnerdcat.snc

import org.junit.Assert.assertArrayEquals
import org.junit.Test

/**
 * Verifies Binlog.appendRecord (KotlinLog.kt) produces byte-identical output
 * to the real Go implementation (tunnel_cat/binlog.AppendRecord) for the
 * same inputs. These expected hex strings were generated by actually
 * running the Go code (`binlog.AppendRecord(nil, tag, []byte(payload))`),
 * not derived by re-deriving the algorithm a second time -- a hand-ported
 * CRC16/uvarint implementation is exactly the kind of thing that can look
 * plausible while being subtly wrong (e.g. missing an intermediate 16-bit
 * truncation during CRC table generation, which doesn't fail loudly, it
 * just silently produces a different table), so this cross-checks against
 * a real reference rather than trusting the port by inspection.
 */
class BinlogTest {

    private fun hex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it) }

    private fun fromHex(s: String): ByteArray =
        ByteArray(s.length / 2) { i -> s.substring(i * 2, i * 2 + 2).toInt(16).toByte() }

    @Test
    fun matchesGoReference_tagSystem_shortAscii() {
        val got = Binlog.appendRecord(7, "hello".toByteArray(Charsets.UTF_8))
        assertArrayEquals(fromHex("c5a7070568656c6c6f68e97a5c"), got)
    }

    @Test
    fun matchesGoReference_tagSystem_realLogLine() {
        val payload = "2026/08/17 10:39:05 [kl] user: connect button pressed\n"
        val got = Binlog.appendRecord(7, payload.toByteArray(Charsets.UTF_8))
        assertArrayEquals(
            fromHex(
                "c5a70736323032362f30382f31372031303a33393a3035205b6b6c5d20757365723a20636f6e6e65637420" +
                    "627574746f6e20707265737365640a49067a5c"
            ),
            got,
        )
    }

    @Test
    fun matchesGoReference_tagGeneric_emptyPayload() {
        val got = Binlog.appendRecord(0, ByteArray(0))
        assertArrayEquals(fromHex("c5a700001d0f7a5c"), got)
    }

    @Test
    fun matchesGoReference_tagSocks5_singleByte() {
        val got = Binlog.appendRecord(2, "a".toByteArray(Charsets.UTF_8))
        assertArrayEquals(fromHex("c5a7020161ed4a7a5c"), got)
    }

    // Belt-and-suspenders: hex() round-trips through fromHex() correctly,
    // so a failure above is a real mismatch, not a test-helper bug.
    @Test
    fun hexHelpersRoundTrip() {
        val sample = byteArrayOf(0x00, 0x1, 0x7F.toByte(), 0xFF.toByte(), 0xC5.toByte(), 0xA7.toByte())
        assertArrayEquals(sample, fromHex(hex(sample)))
    }
}
