// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

//go:build windows

package windows

// stringsEN holds the English (default/fallback) UI strings, keyed by short
// identifiers referenced via T(key) throughout the windows package.
var stringsEN = map[string]string{
	// -- App-wide --
	"app_title":             "ShortNerdCat",
	"app_title_dash_prefix": "ShortNerdCat -- ",
	"ok":                    "OK",
	"cancel":                "Cancel",
	"show":                  "Show",
	"hide":                  "Hide",

	// -- Activation key dialog (dialog.go) --
	"key_dialog_title":             "ShortNerdCat -- Activation Key",
	"key_entry_label":              "Enter your activation key:",
	"scan_from_image":              "Scan from Image",
	"log_in_instead":               "Log In Instead",
	"qr_scan_error_title":          "QR Scan Error",
	"qr_scan_error_msg":            "Could not read QR code:\n\n",
	"invalid_key_title":            "Invalid Key",
	"invalid_key_msg":              "The activation key is not valid:\n\n",
	"update_available_msg":         "A new version (%s) has been downloaded and is ready to install.\n\nRestart now to update?",
	"update_failed_msg":            "ShortNerdCat could not confirm the previous version had fully closed, so the update was NOT applied to avoid corrupting the install.\n\nPlease close ShortNerdCat completely (check the system tray) and start it again.",
	"single_instance_conflict_msg": "ShortNerdCat is already running, and this copy could not close it automatically.\n\nPlease close ShortNerdCat completely (check the system tray) and start it again.",

	// -- Login dialog (dialog_auth.go) --
	"login_dialog_title": "ShortNerdCat -- Log In",
	"email_label":        "Email:",
	"password_label":     "Password:",
	"login_button":       "Login",
	"i_have_a_key":       "I Have a Key",

	// -- Recommend-a-member dialog (dialog_recommend.go) --
	"recommend_dialog_title": "ShortNerdCat -- Recommend a Member",
	"recommend_label":        "Username to recommend for Cat Club:",
	"recommend_button":       "Recommend",

	// -- Tray menu items + tooltips (tray.go) --
	"tray_open":             "Open ShortNerdCat",
	"tray_open_tip":         "Open the main window",
	"tray_login_tip":        "Enter activation key",
	"tray_logout":           "Logout",
	"tray_logout_tip":       "Log out",
	"tray_connect":          "Connect",
	"tray_connect_tip":      "Start the VPN tunnel",
	"tray_disconnect":       "Disconnect",
	"tray_disconnect_tip":   "Stop the VPN tunnel",
	"tray_doh":              "DNS over HTTPS",
	"tray_doh_tip":          "Route DNS through the tunnel using HTTPS -- prevents ISP interference with DNS responses",
	"tray_block_quic":       "Disable QUIC",
	"tray_block_quic_tip":   "Block QUIC/HTTP3 (UDP:443) -- improves video quality on congested connections",
	"tray_region_prefix":    "Region: ",
	"tray_region_tip":       "Select your region for in-country routing",
	"tray_region_auto_tip":  "Detect region automatically",
	"tray_region_other_tip": "Other / no specific region preference",
	"tray_about":            "About",
	"tray_about_tip":        "About ShortNerdCat",
	"tray_update":           "Update available",
	"tray_update_tip":       "Install downloaded update and restart",
	"tray_quit":             "Quit",
	"tray_quit_tip":         "Quit ShortNerdCat",

	// -- Region names (shared by tray + menu bar + settings combobox) --
	"region_auto":        "Auto",
	"region_auto_detect": "Auto (detect)",
	"region_russia":      "Russia",
	"region_europe":      "Europe",
	"region_usa":         "USA",
	"region_usa_full":    "United States",
	"region_china":       "China",
	"region_other":       "Other",

	// -- Tray dynamic tooltip/status fragments --
	"tooltip_not_logged_in":   "ShortNerdCat -- not logged in",
	"tooltip_logging_in":      "ShortNerdCat -- logging in...",
	"tooltip_login_failed":    "ShortNerdCat -- login failed: ",
	"err_login_failed":        "Login failed: ",
	"tooltip_connecting":      "ShortNerdCat -- Connecting...",
	"tooltip_error_prefix":    "ShortNerdCat -- Error: ",
	"tooltip_connected_fmt":   "ShortNerdCat -- Connected  %02d:%02d:%02d",
	"tooltip_cancelling":      "ShortNerdCat -- Cancelling...",
	"tooltip_disconnecting":   "ShortNerdCat -- Disconnecting...",
	"tooltip_login_error":     "ShortNerdCat -- Login error",
	"err_login_rejected":      "Login error -- your key was rejected",
	"err_key_rejected_msg":    "Your ShortNerdCat key was rejected by the server and can no longer be used.\n\nPlease log in again.",
	"tooltip_quitting":        "ShortNerdCat -- Quitting...",
	"err_connection_lost":     "Connection lost",
	"tooltip_connection_lost": "ShortNerdCat -- Connection lost",
	"err_connect_failed":      "Connect failed: ",

	// -- Main window menu bar (uiwindow.go) --
	"menu_region":            "Region",
	"preview_regular":        "Regular",
	"preview_cat_club":       "Cat Club",
	"preview_elite_cat_club": "Elite Cat Club",
	"menu_preview_theme":     "Preview Theme",
	"menu_recommend":         "Recommend new Cat Club members",

	// -- Main window status bar / tabs / buttons / settings labels --
	"status_disconnected":         "Disconnected",
	"status_error":                "Error",
	"status_connected":            "Connected",
	"status_connecting":           "Connecting...",
	"status_disconnecting":        "Disconnecting...",
	"button_connect":              "CONNECT",
	"button_disconnect":           "DISCONNECT",
	"tab_tunnel":                  "TUNNEL",
	"tab_settings":                "SETTINGS",
	"section_your_location":       "YOUR LOCATION",
	"label_your_location":         "Your location (where you are):",
	"section_connection_options":  "CONNECTION OPTIONS",
	"checkbox_doh":                "Use DNS over HTTPS",
	"badge_cat_club_member":       "Cat Club Member",
	"badge_elite_cat_club_member": "Elite Cat Club Member",
}

// stringsRU holds Russian translations. Any key missing here falls back to
// stringsEN automatically via T().
var stringsRU = map[string]string{
	"app_title":             "ShortNerdCat",
	"app_title_dash_prefix": "ShortNerdCat - ",
	"ok":                    "ОК",
	"cancel":                "Отмена",
	"show":                  "Показать",
	"hide":                  "Скрыть",

	"key_dialog_title":             "ShortNerdCat - Ключ активации",
	"key_entry_label":              "Введите ключ активации:",
	"scan_from_image":              "Сканировать с изображения",
	"log_in_instead":               "Войти вместо этого",
	"qr_scan_error_title":          "Ошибка сканирования QR-кода",
	"qr_scan_error_msg":            "Не удалось прочитать QR-код:\n\n",
	"invalid_key_title":            "Неверный ключ",
	"invalid_key_msg":              "Ключ активации неверен:\n\n",
	"update_available_msg":         "Новая версия (%s) уже загружена и готова к установке.\n\nПерезапустить сейчас для обновления?",
	"update_failed_msg":            "ShortNerdCat не смог подтвердить, что предыдущая версия полностью закрылась, поэтому обновление НЕ было применено, чтобы не повредить установку.\n\nЗакройте ShortNerdCat полностью (проверьте системный трей) и запустите заново.",
	"single_instance_conflict_msg": "ShortNerdCat уже запущен, и эта копия не смогла закрыть его автоматически.\n\nЗакройте ShortNerdCat полностью (проверьте системный трей) и запустите заново.",

	"login_dialog_title": "ShortNerdCat - Вход",
	"email_label":        "Email:",
	"password_label":     "Пароль:",
	"login_button":       "Войти",
	"i_have_a_key":       "У меня есть ключ",

	"recommend_dialog_title": "ShortNerdCat - Рекомендация участника",
	"recommend_label":        "Имя пользователя для рекомендации в Cat Club:",
	"recommend_button":       "Рекомендовать",

	"tray_open":             "Открыть ShortNerdCat",
	"tray_open_tip":         "Открыть главное окно",
	"tray_login_tip":        "Ввести ключ активации",
	"tray_logout":           "Выйти",
	"tray_logout_tip":       "Выйти из аккаунта",
	"tray_connect":          "Подключиться",
	"tray_connect_tip":      "Запустить VPN-туннель",
	"tray_disconnect":       "Отключиться",
	"tray_disconnect_tip":   "Остановить VPN-туннель",
	"tray_doh":              "DNS поверх HTTPS",
	"tray_doh_tip":          "Направлять DNS через туннель по HTTPS - предотвращает вмешательство провайдера в DNS-ответы",
	"tray_block_quic":       "Отключить QUIC",
	"tray_block_quic_tip":   "Блокировать QUIC/HTTP3 (UDP:443) - улучшает качество видео на перегруженных соединениях",
	"tray_region_prefix":    "Регион: ",
	"tray_region_tip":       "Выберите свой регион для маршрутизации внутри страны",
	"tray_region_auto_tip":  "Определять регион автоматически",
	"tray_region_other_tip": "Другой / без определённых предпочтений по региону",
	"tray_about":            "О программе",
	"tray_about_tip":        "О программе ShortNerdCat",
	"tray_update":           "Доступно обновление",
	"tray_update_tip":       "Установить загруженное обновление и перезапустить",
	"tray_quit":             "Выход",
	"tray_quit_tip":         "Выйти из ShortNerdCat",

	"region_auto":        "Авто",
	"region_auto_detect": "Авто (определить)",
	"region_russia":      "Россия",
	"region_europe":      "Европа",
	"region_usa":         "США",
	"region_usa_full":    "Соединённые Штаты",
	"region_china":       "Китай",
	"region_other":       "Другой",

	"tooltip_not_logged_in":   "ShortNerdCat - не выполнен вход",
	"tooltip_logging_in":      "ShortNerdCat - выполняется вход...",
	"tooltip_login_failed":    "ShortNerdCat - ошибка входа: ",
	"err_login_failed":        "Ошибка входа: ",
	"tooltip_connecting":      "ShortNerdCat - Подключение...",
	"tooltip_error_prefix":    "ShortNerdCat - Ошибка: ",
	"tooltip_connected_fmt":   "ShortNerdCat - Подключено  %02d:%02d:%02d",
	"tooltip_cancelling":      "ShortNerdCat - Отмена...",
	"tooltip_disconnecting":   "ShortNerdCat - Отключение...",
	"tooltip_login_error":     "ShortNerdCat - Ошибка входа",
	"err_login_rejected":      "Ошибка входа - ваш ключ был отклонён",
	"err_key_rejected_msg":    "Ваш ключ ShortNerdCat был отклонён сервером и больше не может использоваться.\n\nПожалуйста, войдите снова.",
	"tooltip_quitting":        "ShortNerdCat - Завершение...",
	"err_connection_lost":     "Соединение потеряно",
	"tooltip_connection_lost": "ShortNerdCat - Соединение потеряно",
	"err_connect_failed":      "Ошибка подключения: ",

	"menu_region":            "Регион",
	"preview_regular":        "Обычный",
	"preview_cat_club":       "Cat Club",
	"preview_elite_cat_club": "Elite Cat Club",
	"menu_preview_theme":     "Предпросмотр темы",
	"menu_recommend":         "Рекомендовать новых участников Cat Club",

	"status_disconnected":         "Отключено",
	"status_error":                "Ошибка",
	"status_connected":            "Подключено",
	"status_connecting":           "Подключение...",
	"status_disconnecting":        "Отключение...",
	"button_connect":              "ПОДКЛЮЧИТЬСЯ",
	"button_disconnect":           "ОТКЛЮЧИТЬСЯ",
	"tab_tunnel":                  "ТУННЕЛЬ",
	"tab_settings":                "НАСТРОЙКИ",
	"section_your_location":       "ВАШЕ МЕСТОНАХОЖДЕНИЕ",
	"label_your_location":         "Ваше местонахождение (где вы находитесь):",
	"section_connection_options":  "ПАРАМЕТРЫ ПОДКЛЮЧЕНИЯ",
	"checkbox_doh":                "Использовать DNS поверх HTTPS",
	"badge_cat_club_member":       "Участник Cat Club",
	"badge_elite_cat_club_member": "Участник Elite Cat Club",
}
